#################################
## Hugo settings               ##
#################################

baseURL = "/"
DefaultContentLanguage = "en"
relativeURLs = false
languageCode = "en-us"
title = "blog.jemu.name"
#theme = ["jemsugo", "hugo-coder"]
metaDataFormat = "yaml"
#Paginate = 10

[module]
[module.hugoVersion]
min = "0.104.3" # Due to headings render hook
[[module.imports]]
path = "github.com/jemus42/hugo-rstats-pkg-meta"
[[module.imports]]
path = "github.com/jemus42/jemsugo"
[[module.imports]]
path = "github.com/luizdepra/hugo-coder"

# Enable features
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

# Rmarkdown special handling
ignoreFiles = [
  "\\.Rmd$",
  "\\.Rmarkdown$",
  "_cache$",         # Generally recommended settings
  "\\.knit\\.md$",
  "\\.utf8\\.md$",
  "\\.tmp\\.html$",  # Knitr temp files just in case
  "\\.lock$",
  "^renv$",          # Ignore renv if used within page bundles
  "\\.graffle$",     # Diagrams
  "^knitr-hooks\\.",
]

#ignoreFiles = [
#  "\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"
#  ]

[permalinks]
posts = "/:year/:month/:slug/"

[taxonomies]
#category = "categories"
tag = "tags"
series = "series"
#package = "packages" # No theme support yet
#show = "shows"       # No theme support yet

[markup]
defaultMarkdownHandler = "goldmark"
[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false         # Use classes + css if false
# style = "monokai" # only applies with noClasses = true I think? needs RTFM
tabWidth = 2
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.parser]
attribute = true
autoHeadingID = true
autoHeadingIDType = "github"
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = true
[privacy.instagram]
disable = true
[privacy.x]
disable = true
[privacy.vimeo]
disable = true
[privacy.youtube]
disable = true

#################################
## Theme-specific settings     ##
#################################

# Added matomo via hardcoded values in matomo.js to avoid more theme layout overrides
# [Params.matomo]
#   id = "2"
#   server = "matomo.jemu.name"

[languages]
[languages.en]
languagename = "English"

[languages.en.menu]

[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"

[[languages.en.menu.main]]
name = "Posts"
weight = 1
url = "posts/"
