---
title: Quickly Compare your TV show ratings to trakt.tv
author: jemus42
date: '2017-07-20'
categories:
  - rstats
  - tvshows
tags:
  - trakt.tv
  - IMDb
  - Rmd
  - snippet
editor_options:
  chunk_output_type: console
---

```{r init, include = F}
source(rprojroot::find_rstudio_root_file("global.R"))
```

I've posted this little snippet a while ago, but I thought it would be nice to update it to work again.

<!--more-->

```{r trakt-vs-me, message=FALSE, cache=TRUE}
library(tRakt) # devtools::install_github("jemus42/tRakt")
library(dplyr)
library(tidyr)
library(ggplot2)

# Set your username
get_trakt_credentials(username = "jemus42")

show <- trakt.search("Game of Thrones")

trakt.user.ratings(type = "episodes") %>%
  filter(show.slug == show$ids$slug) %>%
  arrange(season, episode) %>%
  select(rating, season, episode, title) %>%
  mutate(season = factor(season, ordered = T)) %>%
  rename(user.rating = rating) %>%
  left_join((trakt.get_all_episodes(show$ids$slug) %>% 
               select(rating, title, episode_abs))) %>%
  gather("type", value = "rating", user.rating, rating) %>%
  filter(season != "0") -> episodes

ggplot(data = episodes, aes(x = episode_abs, y = rating, colour = type)) +
  geom_point(size = 6, colour = "black") +
  geom_point(size = 5) +
  scale_y_continuous(breaks = seq(0, 10, 1), minor_breaks = seq(0, 10, .5)) +
  scale_colour_manual(labels = c("Trakt.tv Rating", "My Rating"),
                        values = c("red", "blue")) +
  labs(title = paste0(show$title, ": trakt.tv Ratings vs. My Own"),
       subtitle = paste("Ratings as of", format(Sys.Date())),
       x = "Absolute Episode #", y = "Rating (0-10)", colour = "Source") +
  theme(legend.position = "top")
```
