---
title: "Testing things"
author: jemus42
date: '2000-01-01'
slug: "post-testing"
categories:
  - debug
nocomment: yes
debug: true
nosocialsharing: yes
notoc: yes
noread: yes
enable_mathjax: no
enable_katex: no
lightbox: true
---

```{r init, include = F}
source(rprojroot::find_rstudio_root_file("global.R"))
library(svglite)
library(knitr)
library(ggplot2)

# knitr::opts_chunk$set(dev = "svglite",
#                       fig.ext = "svg")
```

## Plot output hook

This is a test of knitr plot output customization. 

```{r svgout, dev="svglite", fig.ext='svg', cache=F, eval=F}
ggplot(data = mtcars, aes(x = wt, y = mpg)) +
  geom_point(alpha = .9)
```

```{r pngout, dev='png', fig.ext="png", cache=F}

ggplot(data = mtcars, aes(x = wt, y = mpg)) +
  geom_point(alpha = .9)
```

## Option Overview

### opts_knit

```{r knit-opts}
opts_knit$get()
```

### opts_current

```{r knit-opts-current, eval = FALSE}
opts_current$get()
```

### opts_chunk

```{r knit-opts-chunk, eval = FALSE}
opts_chunk$get()
```


## hooks

```{r hooks}
knitr::knit_hooks$get()
```

